version: "3"
services:
  nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - "8080:8080"
    depends_on:
      - "php7.0"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./socket/:/run/php
      - ./nginx/log:/var/log/nginx
    environment:
      TZ: "Asia/Tokyo"

  php7.0:
    build: ./php
    container_name: "php"
    ports:
      - "9000:9000"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/www.conf:/etc/php/7.0/fpm/www.conf
      - ./php/config/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf
      - ./socket:/run/php
      - ./php/log:/var/log